/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppPProjectIdRouteImport } from './routes/_authenticated/app.p.$projectId'
import { Route as AuthenticatedAppPProjectIdIndexRouteImport } from './routes/_authenticated/app.p.$projectId.index'
import { Route as AuthenticatedAppPProjectIdBoardRouteImport } from './routes/_authenticated/app.p.$projectId.board'
import { Route as AuthenticatedAppPProjectIdMilestonesRouteImport } from './routes/_authenticated/app.p.$projectId.milestones'
import { Route as AuthenticatedAppPProjectIdTeamRouteImport } from './routes/_authenticated/app.p.$projectId.team'
import { Route as AuthenticatedAppPProjectIdChatChannelIdRouteImport } from './routes/_authenticated/app.p.$projectId.chat.$channelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPProjectIdRoute =
  AuthenticatedAppPProjectIdRouteImport.update({
    id: '/p/$projectId',
    path: '/p/$projectId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPProjectIdIndexRoute =
  AuthenticatedAppPProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPProjectIdRoute,
  } as any)
const AuthenticatedAppPProjectIdBoardRoute =
  AuthenticatedAppPProjectIdBoardRouteImport.update({
    id: '/board',
    path: '/board',
    getParentRoute: () => AuthenticatedAppPProjectIdRoute,
  } as any)
const AuthenticatedAppPProjectIdMilestonesRoute =
  AuthenticatedAppPProjectIdMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => AuthenticatedAppPProjectIdRoute,
  } as any)
const AuthenticatedAppPProjectIdTeamRoute =
  AuthenticatedAppPProjectIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedAppPProjectIdRoute,
  } as any)
const AuthenticatedAppPProjectIdChatChannelIdRoute =
  AuthenticatedAppPProjectIdChatChannelIdRouteImport.update({
    id: '/chat/$channelId',
    path: '/chat/$channelId',
    getParentRoute: () => AuthenticatedAppPProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/p/$projectId': typeof AuthenticatedAppPProjectIdRouteWithChildren
  '/app/p/$projectId/board': typeof AuthenticatedAppPProjectIdBoardRoute
  '/app/p/$projectId/milestones': typeof AuthenticatedAppPProjectIdMilestonesRoute
  '/app/p/$projectId/team': typeof AuthenticatedAppPProjectIdTeamRoute
  '/app/p/$projectId/': typeof AuthenticatedAppPProjectIdIndexRoute
  '/app/p/$projectId/chat/$channelId': typeof AuthenticatedAppPProjectIdChatChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/p/$projectId/board': typeof AuthenticatedAppPProjectIdBoardRoute
  '/app/p/$projectId/milestones': typeof AuthenticatedAppPProjectIdMilestonesRoute
  '/app/p/$projectId/team': typeof AuthenticatedAppPProjectIdTeamRoute
  '/app/p/$projectId': typeof AuthenticatedAppPProjectIdIndexRoute
  '/app/p/$projectId/chat/$channelId': typeof AuthenticatedAppPProjectIdChatChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/p/$projectId': typeof AuthenticatedAppPProjectIdRouteWithChildren
  '/_authenticated/app/p/$projectId/board': typeof AuthenticatedAppPProjectIdBoardRoute
  '/_authenticated/app/p/$projectId/milestones': typeof AuthenticatedAppPProjectIdMilestonesRoute
  '/_authenticated/app/p/$projectId/team': typeof AuthenticatedAppPProjectIdTeamRoute
  '/_authenticated/app/p/$projectId/': typeof AuthenticatedAppPProjectIdIndexRoute
  '/_authenticated/app/p/$projectId/chat/$channelId': typeof AuthenticatedAppPProjectIdChatChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/settings'
    | '/app/'
    | '/app/p/$projectId'
    | '/app/p/$projectId/board'
    | '/app/p/$projectId/milestones'
    | '/app/p/$projectId/team'
    | '/app/p/$projectId/'
    | '/app/p/$projectId/chat/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/settings'
    | '/app'
    | '/app/p/$projectId/board'
    | '/app/p/$projectId/milestones'
    | '/app/p/$projectId/team'
    | '/app/p/$projectId'
    | '/app/p/$projectId/chat/$channelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/p/$projectId'
    | '/_authenticated/app/p/$projectId/board'
    | '/_authenticated/app/p/$projectId/milestones'
    | '/_authenticated/app/p/$projectId/team'
    | '/_authenticated/app/p/$projectId/'
    | '/_authenticated/app/p/$projectId/chat/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/$projectId': {
      id: '/_authenticated/app/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/app/p/$projectId'
      preLoaderRoute: typeof AuthenticatedAppPProjectIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/$projectId/': {
      id: '/_authenticated/app/p/$projectId/'
      path: '/'
      fullPath: '/app/p/$projectId/'
      preLoaderRoute: typeof AuthenticatedAppPProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppPProjectIdRoute
    }
    '/_authenticated/app/p/$projectId/board': {
      id: '/_authenticated/app/p/$projectId/board'
      path: '/board'
      fullPath: '/app/p/$projectId/board'
      preLoaderRoute: typeof AuthenticatedAppPProjectIdBoardRouteImport
      parentRoute: typeof AuthenticatedAppPProjectIdRoute
    }
    '/_authenticated/app/p/$projectId/milestones': {
      id: '/_authenticated/app/p/$projectId/milestones'
      path: '/milestones'
      fullPath: '/app/p/$projectId/milestones'
      preLoaderRoute: typeof AuthenticatedAppPProjectIdMilestonesRouteImport
      parentRoute: typeof AuthenticatedAppPProjectIdRoute
    }
    '/_authenticated/app/p/$projectId/team': {
      id: '/_authenticated/app/p/$projectId/team'
      path: '/team'
      fullPath: '/app/p/$projectId/team'
      preLoaderRoute: typeof AuthenticatedAppPProjectIdTeamRouteImport
      parentRoute: typeof AuthenticatedAppPProjectIdRoute
    }
    '/_authenticated/app/p/$projectId/chat/$channelId': {
      id: '/_authenticated/app/p/$projectId/chat/$channelId'
      path: '/chat/$channelId'
      fullPath: '/app/p/$projectId/chat/$channelId'
      preLoaderRoute: typeof AuthenticatedAppPProjectIdChatChannelIdRouteImport
      parentRoute: typeof AuthenticatedAppPProjectIdRoute
    }
  }
}

interface AuthenticatedAppPProjectIdRouteChildren {
  AuthenticatedAppPProjectIdBoardRoute: typeof AuthenticatedAppPProjectIdBoardRoute
  AuthenticatedAppPProjectIdMilestonesRoute: typeof AuthenticatedAppPProjectIdMilestonesRoute
  AuthenticatedAppPProjectIdTeamRoute: typeof AuthenticatedAppPProjectIdTeamRoute
  AuthenticatedAppPProjectIdIndexRoute: typeof AuthenticatedAppPProjectIdIndexRoute
  AuthenticatedAppPProjectIdChatChannelIdRoute: typeof AuthenticatedAppPProjectIdChatChannelIdRoute
}

const AuthenticatedAppPProjectIdRouteChildren: AuthenticatedAppPProjectIdRouteChildren =
  {
    AuthenticatedAppPProjectIdBoardRoute: AuthenticatedAppPProjectIdBoardRoute,
    AuthenticatedAppPProjectIdMilestonesRoute:
      AuthenticatedAppPProjectIdMilestonesRoute,
    AuthenticatedAppPProjectIdTeamRoute: AuthenticatedAppPProjectIdTeamRoute,
    AuthenticatedAppPProjectIdIndexRoute: AuthenticatedAppPProjectIdIndexRoute,
    AuthenticatedAppPProjectIdChatChannelIdRoute:
      AuthenticatedAppPProjectIdChatChannelIdRoute,
  }

const AuthenticatedAppPProjectIdRouteWithChildren =
  AuthenticatedAppPProjectIdRoute._addFileChildren(
    AuthenticatedAppPProjectIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPProjectIdRoute: typeof AuthenticatedAppPProjectIdRouteWithChildren
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPProjectIdRoute: AuthenticatedAppPProjectIdRouteWithChildren,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
