/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppPProjectIdRouteImport } from './routes/_authenticated/app.p.$projectId'
import { Route as AuthenticatedAppPBoardRouteImport } from './routes/_authenticated/app.p..board'
import { Route as AuthenticatedAppPMilestonesRouteImport } from './routes/_authenticated/app.p..milestones'
import { Route as AuthenticatedAppPTeamRouteImport } from './routes/_authenticated/app.p..team'
import { Route as AuthenticatedAppPProjectIdIndexRouteImport } from './routes/_authenticated/app.p.$projectId.index'
import { Route as AuthenticatedAppPChatRouteImport } from './routes/_authenticated/app.p..chat.'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPProjectIdRoute =
  AuthenticatedAppPProjectIdRouteImport.update({
    id: '/p/$projectId',
    path: '/p/$projectId',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPBoardRoute = AuthenticatedAppPBoardRouteImport.update({
  id: '/p/board',
  path: '/p/board',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPMilestonesRoute =
  AuthenticatedAppPMilestonesRouteImport.update({
    id: '/p/milestones',
    path: '/p/milestones',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPTeamRoute = AuthenticatedAppPTeamRouteImport.update({
  id: '/p/team',
  path: '/p/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPProjectIdIndexRoute =
  AuthenticatedAppPProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPProjectIdRoute,
  } as any)
const AuthenticatedAppPChatRoute = AuthenticatedAppPChatRouteImport.update({
  id: '/p/chat/',
  path: '/p/chat/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/p/$projectId': typeof AuthenticatedAppPProjectIdRouteWithChildren
  '/app/p/board': typeof AuthenticatedAppPBoardRoute
  '/app/p/milestones': typeof AuthenticatedAppPMilestonesRoute
  '/app/p/team': typeof AuthenticatedAppPTeamRoute
  '/app/p/chat/': typeof AuthenticatedAppPChatRoute
  '/app/p/$projectId/': typeof AuthenticatedAppPProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/p/board': typeof AuthenticatedAppPBoardRoute
  '/app/p/milestones': typeof AuthenticatedAppPMilestonesRoute
  '/app/p/team': typeof AuthenticatedAppPTeamRoute
  '/app/p/chat': typeof AuthenticatedAppPChatRoute
  '/app/p/$projectId': typeof AuthenticatedAppPProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/p/$projectId': typeof AuthenticatedAppPProjectIdRouteWithChildren
  '/_authenticated/app/p/board': typeof AuthenticatedAppPBoardRoute
  '/_authenticated/app/p/milestones': typeof AuthenticatedAppPMilestonesRoute
  '/_authenticated/app/p/team': typeof AuthenticatedAppPTeamRoute
  '/_authenticated/app/p/chat/': typeof AuthenticatedAppPChatRoute
  '/_authenticated/app/p/$projectId/': typeof AuthenticatedAppPProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/settings'
    | '/app/'
    | '/app/p/$projectId'
    | '/app/p/board'
    | '/app/p/milestones'
    | '/app/p/team'
    | '/app/p/chat/'
    | '/app/p/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/settings'
    | '/app'
    | '/app/p/board'
    | '/app/p/milestones'
    | '/app/p/team'
    | '/app/p/chat'
    | '/app/p/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/p/$projectId'
    | '/_authenticated/app/p/board'
    | '/_authenticated/app/p/milestones'
    | '/_authenticated/app/p/team'
    | '/_authenticated/app/p/chat/'
    | '/_authenticated/app/p/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/$projectId': {
      id: '/_authenticated/app/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/app/p/$projectId'
      preLoaderRoute: typeof AuthenticatedAppPProjectIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/board': {
      id: '/_authenticated/app/p/board'
      path: '/p/board'
      fullPath: '/app/p/board'
      preLoaderRoute: typeof AuthenticatedAppPBoardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/milestones': {
      id: '/_authenticated/app/p/milestones'
      path: '/p/milestones'
      fullPath: '/app/p/milestones'
      preLoaderRoute: typeof AuthenticatedAppPMilestonesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/team': {
      id: '/_authenticated/app/p/team'
      path: '/p/team'
      fullPath: '/app/p/team'
      preLoaderRoute: typeof AuthenticatedAppPTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/p/$projectId/': {
      id: '/_authenticated/app/p/$projectId/'
      path: '/'
      fullPath: '/app/p/$projectId/'
      preLoaderRoute: typeof AuthenticatedAppPProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppPProjectIdRoute
    }
    '/_authenticated/app/p/chat/': {
      id: '/_authenticated/app/p/chat/'
      path: '/p/chat'
      fullPath: '/app/p/chat/'
      preLoaderRoute: typeof AuthenticatedAppPChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppPProjectIdRouteChildren {
  AuthenticatedAppPProjectIdIndexRoute: typeof AuthenticatedAppPProjectIdIndexRoute
}

const AuthenticatedAppPProjectIdRouteChildren: AuthenticatedAppPProjectIdRouteChildren =
  {
    AuthenticatedAppPProjectIdIndexRoute: AuthenticatedAppPProjectIdIndexRoute,
  }

const AuthenticatedAppPProjectIdRouteWithChildren =
  AuthenticatedAppPProjectIdRoute._addFileChildren(
    AuthenticatedAppPProjectIdRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppPProjectIdRoute: typeof AuthenticatedAppPProjectIdRouteWithChildren
  AuthenticatedAppPBoardRoute: typeof AuthenticatedAppPBoardRoute
  AuthenticatedAppPMilestonesRoute: typeof AuthenticatedAppPMilestonesRoute
  AuthenticatedAppPTeamRoute: typeof AuthenticatedAppPTeamRoute
  AuthenticatedAppPChatRoute: typeof AuthenticatedAppPChatRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppPProjectIdRoute: AuthenticatedAppPProjectIdRouteWithChildren,
  AuthenticatedAppPBoardRoute: AuthenticatedAppPBoardRoute,
  AuthenticatedAppPMilestonesRoute: AuthenticatedAppPMilestonesRoute,
  AuthenticatedAppPTeamRoute: AuthenticatedAppPTeamRoute,
  AuthenticatedAppPChatRoute: AuthenticatedAppPChatRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
